### ISSUE TITLE
[Feature Request] 添加调用v1/chat/completions选项

### ISSUE THREAD

**Issue by chenxi050402** [cssxsh/mirai-openai-plugin#10]
openai新增了调用gpt-3.5-turbo（chatgpt模型）的选项，花费低还强大，但只能通过https://api.openai.com/v1/chat/completions调用
使用v1/completions会报错

**Comment by chenxi050402** [comment]
可不可以两个接口的选项并存？
有时候聊天模式可能需要换成更低的GPT3模型进行调用

**Comment by cssxsh** [comment]
你可以PR
