### ISSUE TITLE
目前被墙啦, proxy字段如何正确填写?

### ISSUE THREAD

**Issue by yuanbolin** [cssxsh/mirai-openai-plugin#13]
我填写http://127.0.0.1:7890无效, 代理能正常ping通的

**Comment by cssxsh** [comment]
`socks://127.0.0.1:7890`

你这明显不像是 http 的端口

**Comment by yuanbolin** [comment]
是这样吗,是我浅薄了

**Comment by yuanbolin** [comment]
设置后依然失败
![1677830468190](https://user-images.githubusercontent.com/44077734/222664692-1ba1acee-f4c5-4def-a1f6-54f902515340.png)

**Comment by cssxsh** [comment]
你需要升级

**Comment by yuanbolin** [comment]
感谢回复,目前版本为1.2.1依然失败
![1677831346462](https://user-images.githubusercontent.com/44077734/222667868-2132265b-700a-49b4-a8a7-9dd3a41094af.png)

**Comment by cssxsh** [comment]
看不出来什么问题，你这个代理的规则配置好了吗

**Comment by yuanbolin** [comment]
是的 全局代理.ping是可以ping通的

**Comment by yuanbolin** [comment]
![1677832043091](https://user-images.githubusercontent.com/44077734/222670054-b9040d2d-0fa3-43fe-8dbe-d73475d8b9a3.png)
![image](https://user-images.githubusercontent.com/44077734/222670085-85373239-e8c1-4353-aef1-f5f63c18b6a6.png)
![1677832079350](https://user-images.githubusercontent.com/44077734/222670159-e5209058-6464-40c4-bdc1-d32dc129880a.png)

**Comment by 7aGiven** [comment]
> ![1677832043091](https://user-images.githubusercontent.com/44077734/222670054-b9040d2d-0fa3-43fe-8dbe-d73475d8b9a3.png) ![image](https://user-images.githubusercontent.com/44077734/222670085-85373239-e8c1-4353-aef1-f5f63c18b6a6.png) ![1677832079350](https://user-images.githubusercontent.com/44077734/222670159-e5209058-6464-40c4-bdc1-d32dc129880a.png)

你要不要试试把代理关了能不能ping通。😅

**Comment by cssxsh** [comment]
1. ping 通 并不代表就是走了代理 , 而且 ping 也不走代理 (除非你开了虚拟网卡模式), 而且被墙的是 `api.openai.com`
2. 浏览器能打开 `https://api.openai.com/` 才能证明走了代理

**Comment by yuanbolin** [comment]
十分感谢回复. 确实是我的代理问题!
