### ISSUE TITLE
能否支持配置反向代理地址

### ISSUE THREAD

**Issue by bychv** [cssxsh/mirai-openai-plugin#15]
有些场合代理不太方便

**Comment by cssxsh** [comment]
有什么用吗

**Comment by bychv** [comment]
> 有什么用吗

反代openai的api地址避免时时都要代理

**Comment by cssxsh** [comment]
那你不如试试 https://github.com/cssxsh/mirai-openai-plugin/releases/tag/v1.2.2
里面更了点东西，不需要代理也能用

**Comment by bychv** [comment]
> 那你不如试试 https://github.com/cssxsh/mirai-openai-plugin/releases/tag/v1.2.2 里面更了点东西，不需要代理也能用

如果可以还是希望能增加一个备选方案，看你们决定了
