### ISSUE TITLE
聊天模式使用艾特或回复形式

### ISSUE THREAD

**Issue by chrysoljq** [cssxsh/mirai-openai-plugin#16]
在群内使用聊天模式时，希望使用 @机器人 或 回复机器人 的方式触发，而不是每句话都给与回复。

**Comment by cssxsh** [comment]
https://github.com/cssxsh/mirai-openai-plugin/blob/eadcac55a978aa999baf93c67c6897a0f09c7c54/README.md?plain=1#L34-L48

**Comment by chrysoljq** [comment]
`chat_by_at` 设为  `true` 只会导致艾特机器人触发聊天，和 `chat_prefix` 一样，中途还是会对用户的每一句话进行答复。我希望聊天中只答复艾特机器人的部分。

**Comment by cssxsh** [comment]
这需要开一个新的处理分支
你有需要可以PR

**Comment by cssxsh** [comment]
https://github.com/cssxsh/mirai-openai-plugin/releases/tag/v1.3.1
