### ISSUE TITLE
role: system by config

### ISSUE THREAD

**Issue by Rurityan** [cssxsh/mirai-openai-plugin#17]
啥时候可以增加system角色功能呢

**Comment by Rurityan** [comment]
无需每次主动设置，而是可以把机器人的角色设定放在一个配置文件里的那种

**Comment by cssxsh** [comment]
https://github.com/cssxsh/mirai-openai-plugin/tree/v1.3.0#%E9%A2%84%E7%BD%AE%E8%AF%AD%E5%A2%83
