### ISSUE TITLE
AI绘画时，服务器里接收到了图片，但是发不出去

### ISSUE THREAD

**Issue by DRSalieri** [cssxsh/mirai-openai-plugin#2]
![-6fb9026bdf226a9f.jpg](https://user-images.githubusercontent.com/57832639/206097992-0725c13e-929f-4aea-b1ee-0ed0114cbc4e.jpg)
好像是mirai方面的问题？

**Comment by cssxsh** [comment]
这需要知道是不是
图片有特殊的问题

图片缓存在
`data/xyz.cssxsh.mirai.plugin.mirai-openai-plugin/image`
或者
`config/xyz.cssxsh.mirai.plugin.mirai-openai-plugin/image`

**Comment by awslnotbad** [comment]
> 这需要知道是不是 图片有特殊的问题
> 
> 图片缓存在 或者`data/xyz.cssxsh.mirai.plugin.mirai-openai-plugin/image` `config/xyz.cssxsh.mirai.plugin.mirai-openai-plugin/image`

是PNG格式
![AI生成图片](https://i.imgtg.com/2023/02/16/dZw4v.png)
![替代文字](https://i.imgtg.com/2023/02/16/dvM6q.png)

**Comment by cssxsh** [comment]
> > 这需要知道是不是 图片有特殊的问题
> > 图片缓存在 或者`data/xyz.cssxsh.mirai.plugin.mirai-openai-plugin/image` `config/xyz.cssxsh.mirai.plugin.mirai-openai-plugin/image`
> 
> 是PNG格式 ![AI生成图片](https://camo.githubusercontent.com/3346a57ead74dd670c1530348867abd4a5b66f403ab6de415820528f908e7ee4/68747470733a2f2f692e696d6774672e636f6d2f323032332f30322f31362f645a7734762e706e67) ![替代文字](https://camo.githubusercontent.com/89adac1fa375856f2fe773becf9ba397034425b377a2b05ccfb72ee0f7a5f9e7/68747470733a2f2f692e696d6774672e636f6d2f323032332f30322f31362f64764d36712e706e67)

？你发这些有什么用，又看不出和能正常发送的图片的区别，为什么不把图片上传过来

**Comment by awslnotbad** [comment]
我刚服务器上了，刚在上面传了几张原图回复你了，截图比较快我先发截图了
        
    
        
            
        
    
    
        
        

        
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年2月16日 21:03
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [cssxsh/mirai-openai-plugin] AI绘画时，服务器里接收到了图片，但是发不出去 (Issue #2)
        
      
    
  
  





这需要知道是不是 图片有特殊的问题

图片缓存在 或者data/xyz.cssxsh.mirai.plugin.mirai-openai-plugin/image config/xyz.cssxsh.mirai.plugin.mirai-openai-plugin/image



是PNG格式  



？你发这些有什么用，又看不出和能正常发送的图片的区别，为什么不把图片上传过来
