### ISSUE TITLE
proxy配置无效

### ISSUE THREAD

**Issue by Q2297045667** [cssxsh/mirai-openai-plugin#24]
![image](https://user-images.githubusercontent.com/42416195/227758325-8add1af7-95ef-485b-89b7-39b62d767ac2.png)
配置文件填写proxy和token之后，启动仍然提示我填写token
填写之后输出 代理已配置: http
![image](https://user-images.githubusercontent.com/42416195/227758416-2d8af598-709f-49f5-81f4-9c5177e10a7c.png)
再次打开配置文件proxy: http://192.168.1.3:7890就变成了proxy: http
![image](https://user-images.githubusercontent.com/42416195/227758485-65bbce80-c01c-4875-838c-93d19d19af2c.png)
软路由相关的代理端口
![image](https://user-images.githubusercontent.com/42416195/227758521-6e1621a4-3f73-488e-9496-993a9ceaa145.png)
代理路由可以正常打开api.openai.com
代理路由相关规则配置
![image](https://user-images.githubusercontent.com/42416195/227758975-7198410e-b58d-4efa-9c1b-0a1105474a5c.png)

**Comment by Q2297045667** [comment]
机器人是部署在我本地服务器上的，因为一些特殊关系不能走代理路由

**Comment by cssxsh** [comment]
```
proxy: 'http://192.168.1..3:7890'
```
