### ISSUE TITLE
这个是啥报错

### ISSUE THREAD

**Issue by Karensky** [cssxsh/mirai-openai-plugin#27]
![IMG_20230330_223119](https://user-images.githubusercontent.com/59323207/228869916-e7ccc95f-00ee-4362-bb9f-1fb331b36862.jpg)

**Comment by cssxsh** [comment]
你输入的 key 不对

**Comment by cssxsh** [comment]
顺便问下，你们真的把 `****************` 当作 key 的一部分了？ 你们就没觉得这有问题吗
