### ISSUE TITLE
机器人回复吞第一个字符

### ISSUE THREAD

**Issue by Happylinzy** [cssxsh/mirai-openai-plugin#28]
Bug现象：
机器人在回复时会自动吞第一个字。

![810fb94e0c5823e5cd2958f3c1633a3](https://user-images.githubusercontent.com/54973585/229297705-1eb7a8dc-ef46-4ed4-83ad-12501be496eb.png)

原有应为：聊天将开始

Plugin 配置：
fix-protocol-version-1.3.0.mirai2.jar
chat-command-0.5.1.mirai.jar
mirai-api-http-2.9.1.mirai2.jar
mirai-openai-plugin-1.3.4.mirai2.jar

同时在使用的plugin：
pixiv-1.7.5.mirai2.jar
mirai-login-solver-sakura-0.0.9.mirai2.jar
mcl-addon-2.1.1.jar

**Comment by cssxsh** [comment]
这可能是你 `安卓客户端` 或者 `Bot 登录协议` 的问题

**Comment by Happylinzy** [comment]
协议使用MACOS
