### ISSUE TITLE
[功能]添加对ChatGLM API的支持？

### ISSUE THREAD

**Issue by LTHPKBTE** [cssxsh/mirai-openai-plugin#34]
有没有可能让这个插件兼容ChatGLM的API？使用openai经常会有次数上限限制，我想将模型换成ChatGLM-6B在本地运行，但是找不到什么好的方法和mirai互联（因为我不会java）
ChatGLM的API格式：[ChatGLM-6B#api部署](https://github.com/THUDM/ChatGLM-6B#api%E9%83%A8%E7%BD%B2)

重新翻看了一下这个插件的配置和使用，或许我并不应该在这里请求这个功能...但是相关插件只有这几个了，如果不行请直接关闭issue，打扰了。

**Comment by cssxsh** [comment]
如果真的要写那也是另开项目
