### ISSUE TITLE
OpenAI API异常

### ISSUE THREAD

**Issue by wuchen4588** [cssxsh/mirai-openai-plugin#35]
![image](https://github.com/cssxsh/mirai-openai-plugin/assets/60568101/3488749f-e766-4cfa-b299-627b25883590)
已经通过v2rayNG转发socks代理通过流量，可是为什么还是报异常。

**Comment by cssxsh** [comment]
报错信息是空的可还行

**Comment by wuchen4588** [comment]
请问怎么解决这个问题

**Comment by cssxsh** [comment]
不知道，这看起来是梯子引发的问题，我没复现出来
