### ISSUE TITLE
有没有办法知道openai服务器用的是什么方法计算tokens

### ISSUE THREAD

**Issue by hisou** [cssxsh/mirai-openai-plugin#9]
我保持上送很大的max_tokens值来让openai给我返回我的prompt的长度。我试了一下有一些汉字是占俩tokens有一些是占三个tokens，弄得我不知道在正式用的时候怎么设定max_tokens比较好。
![image](https://user-images.githubusercontent.com/13644483/219015319-560badc3-25de-4aae-bb86-f7c26fac2306.png)
这个返回：…… 15 in your prompt ……
![image](https://user-images.githubusercontent.com/13644483/219015712-69d75d2e-77a8-409b-96fa-6f9304a02f3a.png)
这个返回：…… 18 in your prompt ……
![image](https://user-images.githubusercontent.com/13644483/219015828-8a6aceee-f973-4d17-904a-86bddadd1968.png)
![image](https://user-images.githubusercontent.com/13644483/219015898-f0840ef8-ca82-4f1c-8c1f-4266c672e7e0.png)
删掉一个“个”字，返回16了

**Comment by cssxsh** [comment]
可能和 UTF-8 编码有关

**Comment by hisou** [comment]
UTF8固定占三个字节我觉得应该没疑问，可能还是openai对中文语义的分析和英语不同，有点不规律。
本项目的 buffer.length > ChatConfig.maxTokens * 0.6 这个设计是基于何种考虑呢

**Comment by cssxsh** [comment]
> UTF8固定占三个字节我觉得应该没疑问，可能还是openai对中文语义的分析和英语不同，有点不规律。 本项目的 buffer.length > ChatConfig.maxTokens * 0.6 这个设计是基于何种考虑呢

0.6 是魔法数字，主要是从用户角度是无法理解上下文存在上线的，所以我尽可能的给更多的空间
